CocoaPods/blog.cocoapods.org

_posts/2014-12-25-Pod-Authors-Guide-to-CocoaPods-Frameworks.markdown
Thanks to @neonichu & @getaaron.
See this gist: https://gist.github.com/getaaron/73a3a5eb776613681389
=> Add a section about Availabilitiy to "Pod Authors Guide to CocoaPods Frameworks"

.gitignore, _posts/2015-02-21-Test-Jammin.markdown
TheTest Jam blog post.
Thanks @modocache / @lazerwalker
=> @anyone => test jam

_posts/2015-03-11-CocoaPods-0.36.markdown
=> [CocoaPods 0.36] Add paragraph about private pods and "source"

_posts/2015-04-13-Prepare-to-Jam.markdown
What if someone will read this a week later? ;) It should be clear what weekend is referenced. Ideally we might need to specify year too, but I guess it should be fine with at least dates and month ;)
=> Clarify weekend dates in the post about test jam

_posts/2015-04-19-Jamming-2015.markdown
cwRichardKim/RKNotificationHub#10
=> One more PR link

Gemfile.lock, _config.yml, _posts/2015-06-01-2015-CocoaPods-State-of-the-Union.markdown
=> [Post] Add 2015 SotU post

_posts/2015-08-09-Stats-Reset.markdown
=> Blog post on resetting stats with production switch

_posts/2015-08-09-Stats-Reset.markdown
=> Fix typo in "resetting"

_posts/2015-08-26-Running-SSH-Commands-via-Rakefiles.markdown
I could have done with this when I started the SSH stuff. So I'll provide it for the peeps that come after.
=> Add a blog post about automating the cocoadocs shell commands

_posts/2015-10-09-CocoaPods-0.39.markdown
=> [Posts] Add 0.39 release post

_posts/2015-10-27-Capital-One.markdown
=> [Posts] Add Capital One post

_posts/2015-11-07-Creme-de-la-Pods.markdown
Added a blog post announcing @CremeDeLaPods now that it's been a week - @CocoaPods/core
=> Add a blog post about creme de la pods

_posts/2015-11-18-Stats-2015.markdown
=> Fix spelling error

_posts/2014-01-30-Repairing-Our-Broken-Specs-Repository.markdown
Related to https://github.com/CocoaPods/CocoaPods/issues/3539
=> Include fix for failed pod setup

_posts/2016-01-29-CocoaPods-1.0.markdown
Alright, should cover a lot of the whys and provide some good examples of before/afters for common looking podfiles
=> 1.0 migration blog post

_posts/2016-02-03-CocoaPods-1.0.markdown
=> Small typo fix

_posts/2016-01-29-RGSoC.markdown
=> Fix a couple of typos in the RGSoC post

_posts/2016-02-03-CocoaPods-1.0.markdown
* Replacing wrong use of `it's` (short form of `it is`) with `its` (possessive pronoun).
* Adding a space after a full stop, before "It would introduce extremely...".
=> Fixing 2 typos and a missing space

_posts/2016-01-29-RGSoC.markdown
Fixed Typo.
Deleted some wordiness.
=> Edits for Coc'oa'Pods spelling

_posts/2016-01-29-RGSoC.markdown
Cut out an extra O, and got rid of extra space in the What we Worked ……on Section
=> Made some edits

_posts/2016-02-22-Socks.markdown
Just to pass people forwards to the site mainly.
=> Quick Socks post

_drafts/shallow-clone-post-mortem.md
Closes #128.
/cc @CocoaPods/core
=> [draft] Shallow clone post mortem.

_posts/2016-05-29-2016-CocoaPods-State-of-the-Union.markdown
See https://github.com/CocoaPods/sotu.cocoapods.org/pull/17 as well.
\c @orta @mrackwitz @neonichu
=> Add 2016 SotU announcement post

_posts/2016-10-28-Sharding.markdown
Anything missing? /cc @segiddins
=> Sharding Announcement

_posts/2016-10-28-Sharding.markdown
Code blocks break the layout on the index
=> Fixes index layout for sharing post

.vscode/spellchecker.json, _posts/2017-03-28-CocoaDocs-Documentation-Sunsetting.markdown
Pairs with https://github.com/CocoaPods/cocoadocs.org/pull/508
Aims to explain the why, and the how of the upcoming changes to CocoaDocs so that.I can continue to maintain it for a very long time into the future.
=> Post on the simplification of CD

_posts/2018-04-04-CocoaPods-1.5.0.markdown
https://www.merriam-webster.com/dictionary/whet
=> Correct typo

_config.yml, _includes/person.html, _layouts/post.html, _plugins/gravatar_url.rb
Closes #164 
Also fixes some other template URLs.
=> Make some URLs secure
